// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );flutter devices
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7QGbVeO87wYECT4okftYCpxkv3JVeeCI',
    appId: '1:511845299082:android:9f53c8cacb8413d53f8e73',
    messagingSenderId: '511845299082',
    projectId: 'gestion-stock-pme',
    storageBucket: 'gestion-stock-pme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYNhYoaFUPhkKKP6mZXhcLFC3EDTwB1M',
    appId: '1:511845299082:ios:de3a0189c612f43e3f8e73',
    messagingSenderId: '511845299082',
    projectId: 'gestion-stock-pme',
    storageBucket: 'gestion-stock-pme.firebasestorage.app',
    iosBundleId: 'com.example.gestionStockPme',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd7OBTwT6jXMFVBIBi077Yw7TvP_iZroA',
    appId: '1:511845299082:web:49a182f821a1288b3f8e73',
    messagingSenderId: '511845299082',
    projectId: 'gestion-stock-pme',
    authDomain: 'gestion-stock-pme.firebaseapp.com',
    storageBucket: 'gestion-stock-pme.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd7OBTwT6jXMFVBIBi077Yw7TvP_iZroA',
    appId: '1:511845299082:web:ad8f54e78afb149a3f8e73',
    messagingSenderId: '511845299082',
    projectId: 'gestion-stock-pme',
    authDomain: 'gestion-stock-pme.firebaseapp.com',
    storageBucket: 'gestion-stock-pme.firebasestorage.app',
  );

}